# Generated by Django 3.0.7 on 2020-06-29 15:47

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First Name', max_length=300)),
                ('last_name', models.CharField(help_text='Last Name', max_length=300)),
                ('date_of_birth', models.DateField(help_text='Date of birth')),
                ('age', models.IntegerField(help_text='Age', max_length=2)),
                ('sex', models.CharField(help_text='Sex', max_length=10)),
                ('height', models.CharField(help_text='Height', max_length=20)),
                ('weight', models.CharField(help_text='Weight', max_length=20)),
                ('full_address', models.TextField(help_text='Full Address')),
                ('phone_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('alternate_phone', phone_field.models.PhoneField(blank=True, help_text='Alternate phone number', max_length=31)),
                ('membership_start_date', models.DateField(help_text='Start Date of membership')),
                ('membership_end_date', models.DateField(help_text='End Date of membership')),
                ('blood_group', models.CharField(help_text='Blood Group', max_length=20)),
                ('medical_history', models.CharField(help_text='Medical History', max_length=300)),
            ],
        ),
    ]
