# Generated by Django 3.0.7 on 2020-12-19 13:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField(max_length=2)),
                ('sex', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=20)),
                ('full_address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(max_length=20)),
                ('membership_start_date', models.DateField(default=django.utils.timezone.now)),
                ('membership_end_date', models.DateField(default=django.utils.timezone.now)),
                ('blood_group', models.CharField(max_length=20)),
                ('medical_history', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='GenerateInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=300)),
                ('purchased_date', models.DateField(default=django.utils.timezone.now)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('grand_total', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenerateItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=300)),
                ('item_quantity', models.CharField(max_length=300)),
                ('item_amount', models.CharField(max_length=300)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='fitness.GenerateInvoice')),
            ],
        ),
    ]
