# Generated by Django 3.0.7 on 2020-06-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addusers',
            name='age',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='addusers',
            name='alternate_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='addusers',
            name='blood_group',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='addusers',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='addusers',
            name='first_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='addusers',
            name='full_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='addusers',
            name='height',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='addusers',
            name='last_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='addusers',
            name='medical_history',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='addusers',
            name='membership_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='addusers',
            name='membership_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='addusers',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='addusers',
            name='sex',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='addusers',
            name='weight',
            field=models.CharField(max_length=20),
        ),
    ]
