# Generated by Django 3.0.7 on 2020-07-05 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=300)),
                ('item_name', models.CharField(max_length=300)),
                ('item_quantity', models.CharField(max_length=300)),
                ('item_amount', models.CharField(max_length=300)),
                ('item_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
