# Generated by Django 3.0.7 on 2020-08-01 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_generateinvoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generateinvoice',
            old_name='item_date',
            new_name='purchased_date',
        ),
        migrations.RemoveField(
            model_name='generateinvoice',
            name='item_amount',
        ),
        migrations.RemoveField(
            model_name='generateinvoice',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='generateinvoice',
            name='item_quantity',
        ),
        migrations.AddField(
            model_name='generateinvoice',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GenerateItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=300)),
                ('item_quantity', models.CharField(max_length=300)),
                ('item_amount', models.CharField(max_length=300)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='fitness.GenerateInvoice')),
            ],
        ),
    ]
