# Generated by Django 3.0.7 on 2020-10-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_auto_20200801_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateitems',
            name='total_amount',
            field=models.IntegerField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='generateitems',
            name='item_amount',
            field=models.IntegerField(max_length=300),
        ),
        migrations.AlterField(
            model_name='generateitems',
            name='item_quantity',
            field=models.IntegerField(max_length=300),
        ),
    ]
