# Generated by Django 3.0.7 on 2020-10-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_auto_20201009_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateitems',
            name='item_amount',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='generateitems',
            name='item_quantity',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='generateitems',
            name='total_amount',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
