# Generated by Django 3.0.7 on 2020-10-08 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_auto_20201009_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generateitems',
            name='total_amount',
        ),
    ]
