# Generated by Django 3.0.7 on 2020-10-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_remove_generateitems_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateitems',
            name='grand_total',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
