# Generated by Django 3.0.7 on 2020-10-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_generateitems_grand_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generateitems',
            name='grand_total',
        ),
        migrations.AddField(
            model_name='generateinvoice',
            name='grand_total',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
